/* GENERATED by tools/gen-rls.js from assets/js/rbac.js - do not edit here. */
--  Source of truth: assets/js/rbac.js   Regenerate: node tools/gen-rls.js

-- ============================================================
--  013 - PROFILES.ROLE GUARD.
--  RLS is row-scoped, so 008's profiles_update / profiles_insert policies
--  (id = auth.uid() or auth_role() = 'Admin') restrict which ROW a caller
--  touches but not which COLUMN: any signed-in staff member could PATCH their
--  own role to 'Admin' with nothing but the anon key and their own JWT, and
--  the whole UI gate reads its answer from that column. This trigger is the
--  column-level half of that policy. Role vocabulary comes from RBAC.ROLES.
--
--  Apply after 008. Safe to re-run: create or replace + drop trigger first.
-- ============================================================

create or replace function public.profiles_role_guard()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  valid text[] := array['Admin', 'RND Formula', 'RND Kemas', 'Regulatory', 'Marketing', 'PPIC', 'Purchasing', 'Warehouse', 'Production', 'QA', 'Finance'];
begin
  -- A typo'd role grants nothing and stays invisible until it bites, so
  -- reject unknown values on every path including the Dashboard.
  if not (new.role = any (valid)) then
    raise exception 'profiles.role % is not a known role', new.role;
  end if;

  -- No user session: SQL Editor, Table Editor, service_role, or the
  -- handle_new_user trigger. This is the maintenance path and the only way
  -- to create the first Admin, so it is trusted with the role column.
  if auth.uid() is null then return new; end if;

  if tg_op = 'INSERT' then
    -- 008 confines an insert to the caller's own id. A non-Admin - including
    -- anyone whose profile row does not exist yet, where auth_role() is null -
    -- never picks their own role: fall back to the table default. Force rather
    -- than raise, because Sync.ensureProfile() legitimately creates its own row
    -- this way, and an upsert-merge reaches the server as an INSERT.
    if public.auth_role() = 'Admin' then return new; end if;
    new.role := 'PPIC';
    return new;
  end if;

  if new.role is distinct from old.role and public.auth_role() is distinct from 'Admin' then
    raise exception 'profiles.role is managed by Admin only (current role: %)', public.auth_role();
  end if;
  return new;
end $$;

drop trigger if exists profiles_role_guard on public.profiles;
create trigger profiles_role_guard before insert or update on public.profiles
  for each row execute function public.profiles_role_guard();
